// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/braves.tsx";
import * as $1 from "./routes/favicon.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/pizza.tsx";
import * as $4 from "./routes/poems/index.tsx";
import * as $$0 from "./islands/BravesRadioLocator.tsx";
import * as $$1 from "./islands/PizzaCalculator.tsx";

const manifest = {
  routes: {
    "./routes/braves.tsx": $0,
    "./routes/favicon.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/pizza.tsx": $3,
    "./routes/poems/index.tsx": $4,
  },
  islands: {
    "./islands/BravesRadioLocator.tsx": $$0,
    "./islands/PizzaCalculator.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
