// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/braves.tsx";
import * as $2 from "./routes/favicon.ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/pizza.tsx";
import * as $5 from "./routes/poems/[slug].tsx";
import * as $6 from "./routes/poems/index.tsx";
import * as $$0 from "./islands/AfterHours.tsx";
import * as $$1 from "./islands/BravesRadioLocator.tsx";
import * as $$2 from "./islands/NormalHours.tsx";
import * as $$3 from "./islands/PizzaCalculator.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/braves.tsx": $1,
    "./routes/favicon.ts": $2,
    "./routes/index.tsx": $3,
    "./routes/pizza.tsx": $4,
    "./routes/poems/[slug].tsx": $5,
    "./routes/poems/index.tsx": $6,
  },
  islands: {
    "./islands/AfterHours.tsx": $$0,
    "./islands/BravesRadioLocator.tsx": $$1,
    "./islands/NormalHours.tsx": $$2,
    "./islands/PizzaCalculator.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
